name: Cypress Cloud

on: 
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress comand line
        default: cypress/e2e/*

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4.1.7

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: npm install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 64db8c73-f18e-4d44-8a19-6570aa7819cc
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
